[package]
name = "tmpltool"
version = "1.1.1"
edition = "2024"

[dependencies]
tera = { version = "1", features = ["builtins"] }
clap = { version = "4", features = ["derive"] }
regex = "1"
md-5 = "0.10"
sha1 = "0.10"
sha2 = "0.10"
uuid = { version = "1.19", features = ["v4"] }
rand = "0.9"
glob = "0.3"
serde_json = "1"
serde_yaml = "0.9"
toml = "0.8"
